import { IngredientRecord } from '@/types';

// Standard nutritional values (Rostagno et al., 2023; EMBRAPA; UFV)
export const DEFAULT_INGREDIENTS: Omit<IngredientRecord, 'id' | 'createdAt'>[] = [
  {
    name: 'Milho Moído',
    dryMatter: 88,
    protein: 8.8,
    energy: 3350,
    calcium: 0.03,
    phosphorusTotal: 0.28,
    phosphorusAvailable: 0.10,
    sodium: 0.01,
    potassium: 0.36,
    methionine: 0.18,
    metCis: 0.39,
    lysine: 0.27,
    threonine: 0.28,
    tryptophan: 0.07,
    fiber: 2.3,
    etherExtract: 4.0,
    price: 1.5,
    stock: 0,
    dataSource: 'Tabelas Brasileiras para Aves e Suínos – Rostagno et al.',
    referenceYear: 2023,
    lastUpdated: new Date().toISOString(),
    technicalNotes: 'Valores médios para milho moído utilizado na alimentação de aves. Pode variar conforme safra e região.',
    userEditable: true,
  },
  {
    name: 'Farelo de Soja 45%',
    dryMatter: 88,
    protein: 45.0,
    energy: 2450,
    calcium: 0.30,
    phosphorusTotal: 0.70,
    phosphorusAvailable: 0.25,
    sodium: 0.02,
    potassium: 2.00,
    methionine: 0.65,
    metCis: 1.20,
    lysine: 2.75,
    threonine: 1.70,
    tryptophan: 0.60,
    fiber: 3.5,
    etherExtract: 1.0,
    price: 2.2,
    stock: 0,
    dataSource: 'Tabelas Brasileiras para Aves e Suínos – Rostagno et al.',
    referenceYear: 2023,
    lastUpdated: new Date().toISOString(),
    technicalNotes: 'Farelo de soja com 45% de proteína bruta, solvente extraído.',
    userEditable: true,
  },
  {
    name: 'Farelo de Trigo',
    dryMatter: 88,
    protein: 16.0,
    energy: 2200,
    calcium: 0.15,
    phosphorusTotal: 0.90,
    phosphorusAvailable: 0.30,
    sodium: 0.06,
    potassium: 1.10,
    methionine: 0.16,
    metCis: 0.36,
    lysine: 0.55,
    threonine: 0.45,
    tryptophan: 0.16,
    fiber: 9.5,
    etherExtract: 3.5,
    price: 1.0,
    stock: 0,
    dataSource: 'Tabelas Brasileiras para Aves e Suínos – Rostagno et al.',
    referenceYear: 2023,
    lastUpdated: new Date().toISOString(),
    technicalNotes: 'Subproduto da moagem do trigo, fonte de fibra e proteína.',
    userEditable: true,
  },
  {
    name: 'Farelo de Arroz Integral',
    dryMatter: 89,
    protein: 13.5,
    energy: 2800,
    calcium: 0.08,
    phosphorusTotal: 1.10,
    phosphorusAvailable: 0.35,
    sodium: 0.04,
    potassium: 1.30,
    methionine: 0.22,
    metCis: 0.43,
    lysine: 0.54,
    threonine: 0.45,
    tryptophan: 0.14,
    fiber: 11.0,
    etherExtract: 15.0,
    price: 0.9,
    stock: 0,
    dataSource: 'Empresa Brasileira de Pesquisa Agropecuária (EMBRAPA)',
    referenceYear: 2022,
    lastUpdated: new Date().toISOString(),
    technicalNotes: 'Farelo integral de arroz, contendo gordura e fibra.',
    userEditable: true,
  },
  {
    name: 'Sorgo',
    dryMatter: 88,
    protein: 9.5,
    energy: 3300,
    calcium: 0.04,
    phosphorusTotal: 0.32,
    phosphorusAvailable: 0.12,
    sodium: 0.02,
    potassium: 0.35,
    methionine: 0.15,
    metCis: 0.34,
    lysine: 0.25,
    threonine: 0.28,
    tryptophan: 0.06,
    fiber: 2.0,
    etherExtract: 3.5,
    price: 1.4,
    stock: 0,
    dataSource: 'Universidade Federal de Viçosa (UFV)',
    referenceYear: 2023,
    lastUpdated: new Date().toISOString(),
    technicalNotes: 'Sorgo grão, alternativa energética ao milho. Verificar tanino.',
    userEditable: true,
  },
  {
    name: 'Calcário Calcítico',
    dryMatter: 99,
    protein: 0.0,
    energy: 0,
    calcium: 38.0,
    phosphorusTotal: 0.0,
    phosphorusAvailable: 0.0,
    sodium: 0.0,
    potassium: 0.0,
    methionine: 0.0,
    metCis: 0.0,
    lysine: 0.0,
    threonine: 0.0,
    tryptophan: 0.0,
    fiber: 0.0,
    etherExtract: 0.0,
    price: 0.5,
    stock: 0,
    dataSource: 'Literatura científica nacional sobre nutrição de aves',
    referenceYear: 2023,
    lastUpdated: new Date().toISOString(),
    technicalNotes: 'Fonte de cálcio de alta biodisponibilidade para aves em postura.',
    userEditable: true,
  },
  {
    name: 'Fosfato Bicálcico',
    dryMatter: 95,
    protein: 0.0,
    energy: 0,
    calcium: 22.0,
    phosphorusTotal: 19.0,
    phosphorusAvailable: 18.0,
    sodium: 0.0,
    potassium: 0.0,
    methionine: 0.0,
    metCis: 0.0,
    lysine: 0.0,
    threonine: 0.0,
    tryptophan: 0.0,
    fiber: 0.0,
    etherExtract: 0.0,
    price: 3.0,
    stock: 0,
    dataSource: 'Literatura científica nacional sobre nutrição de aves',
    referenceYear: 2023,
    lastUpdated: new Date().toISOString(),
    technicalNotes: 'Fonte de fósforo disponível e cálcio.',
    userEditable: true,
  },
  {
    name: 'Óleo de Soja',
    dryMatter: 100,
    protein: 0.0,
    energy: 8550,
    calcium: 0.0,
    phosphorusTotal: 0.0,
    phosphorusAvailable: 0.0,
    sodium: 0.0,
    potassium: 0.0,
    methionine: 0.0,
    metCis: 0.0,
    lysine: 0.0,
    threonine: 0.0,
    tryptophan: 0.0,
    fiber: 0.0,
    etherExtract: 100.0,
    price: 4.5,
    stock: 0,
    dataSource: 'Tabelas Brasileiras para Aves e Suínos – Rostagno et al.',
    referenceYear: 2023,
    lastUpdated: new Date().toISOString(),
    technicalNotes: 'Óleo vegetal, fonte concentrada de energia.',
    userEditable: true,
  },
  {
    name: 'Sal Comum',
    dryMatter: 100,
    protein: 0.0,
    energy: 0,
    calcium: 0.0,
    phosphorusTotal: 0.0,
    phosphorusAvailable: 0.0,
    sodium: 39.0,
    potassium: 0.0,
    methionine: 0.0,
    metCis: 0.0,
    lysine: 0.0,
    threonine: 0.0,
    tryptophan: 0.0,
    fiber: 0.0,
    etherExtract: 0.0,
    price: 0.3,
    stock: 0,
    dataSource: 'Literatura científica nacional sobre nutrição de aves',
    referenceYear: 2023,
    lastUpdated: new Date().toISOString(),
    technicalNotes: 'Cloreto de sódio, fonte de sódio e cloro.',
    userEditable: true,
  },
  {
    name: 'Núcleo para Postura',
    dryMatter: 95,
    protein: 0.0,
    energy: 0,
    calcium: 0.0,
    phosphorusTotal: 0.0,
    phosphorusAvailable: 0.0,
    sodium: 0.0,
    potassium: 0.0,
    methionine: 0.0,
    metCis: 0.0,
    lysine: 0.0,
    threonine: 0.0,
    tryptophan: 0.0,
    fiber: 0.0,
    etherExtract: 0.0,
    price: 15.0,
    stock: 0,
    dataSource: 'Literatura técnica comercial',
    referenceYear: 2023,
    lastUpdated: new Date().toISOString(),
    technicalNotes: 'Premix vitamínico-mineral para aves de postura (incluir aminoácidos, enzimas, aditivos conforme fórmula).',
    userEditable: true,
  },
];
